name: "Check and reject spam PRs"
description: "Run basic checks and close & mark spam PRs"
author: "Andrey Slotin"
inputs:
  access_token:
    description: "GitHub access token"
    required: true
  pr_num:
    description: "The pull request number (from github.event.pull_request.number)"
    required: true
  forked:
    description: "Whether the PR is from a forked repo (from github.event.head.fork)"
    required: true
  spam_label:
    description: "Spam label text"
    required: false
    default: "Spam"
  close_spam_prs:
    description: "Automatically close spam PRs (yes/no)?"
    required: false
    default: "yes"
runs:
  using: docker
  image: "Dockerfile"
branding:
  icon: "thumbs-down"
  color: "red"
